import React from "react";

export const styles: Record<string, React.CSSProperties> = {
  root: {
    background: "#0A0F1A",
    minHeight: "100vh",
    color: "#E2E8F0",
    fontFamily: "'JetBrains Mono', 'Courier New', monospace",
    position: "relative",
    overflowX: "hidden",
  },
  noise: {
    position: "fixed",
    inset: 0,
    backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)' opacity='0.03'/%3E%3C/svg%3E")`,
    pointerEvents: "none",
    zIndex: 0,
  },
  nav: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 80px",
    borderBottom: "1px solid rgba(59,130,246,0.1)",
    position: "sticky",
    top: 0,
    background: "rgba(10,15,26,0.9)",
    backdropFilter: "blur(12px)",
    zIndex: 100,
  },
  logo: {
    color: "#3B82F6",
    fontWeight: 700,
    fontSize: 18,
    letterSpacing: "0.1em",
  },
  navLinks: { display: "flex", gap: 32 },
  navLink: {
    color: "#94A3B8",
    textDecoration: "none",
    fontSize: 14,
    letterSpacing: "0.05em",
    transition: "color 0.2s",
  },
  navLinkActive: {
    color: "#E2E8F0",
    borderBottom: "2px solid #3B82F6",
    paddingBottom: 2,
  },
  resumeBtn: {
    border: "1px solid #3B82F6",
    background: "transparent",
    color: "#3B82F6",
    padding: "8px 20px",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "inherit",
    letterSpacing: "0.08em",
    transition: "all 0.2s",
  },
  hero: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "100px 80px 80px",
    position: "relative",
    zIndex: 1,
  },
  availableBadge: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 11,
    color: "#10B981",
    letterSpacing: "0.15em",
    border: "1px solid rgba(16,185,129,0.3)",
    padding: "6px 16px",
    borderRadius: 20,
    marginBottom: 32,
    background: "rgba(16,185,129,0.05)",
  },
  dot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "#10B981",
    display: "inline-block",
    boxShadow: "0 0 8px #10B981",
  },
  heroTitle: {
    fontSize: "clamp(32px, 5vw, 56px)",
    fontWeight: 700,
    lineHeight: 1.15,
    margin: "0 0 20px",
    color: "#E2E8F0",
    fontFamily: "'JetBrains Mono', monospace",
  },
  heroAccent: { color: "#10B981" },
  heroSub: {
    color: "#64748B",
    fontSize: 15,
    lineHeight: 1.7,
    maxWidth: 480,
    margin: "0 0 36px",
  },
  heroBtns: { display: "flex", gap: 16, marginBottom: 60 },
  btnPrimary: {
    background: "rgba(59,130,246,0.1)",
    border: "1px solid #3B82F6",
    color: "#E2E8F0",
    padding: "12px 28px",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 14,
    fontFamily: "inherit",
    letterSpacing: "0.05em",
  },
  btnGhost: {
    background: "transparent",
    border: "1px solid rgba(148,163,184,0.3)",
    color: "#94A3B8",
    padding: "12px 28px",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 14,
    fontFamily: "inherit",
    letterSpacing: "0.05em",
  },
  codeWindow: {
    background: "#0D1424",
    border: "1px solid rgba(59,130,246,0.2)",
    borderRadius: 8,
    width: "100%",
    maxWidth: 520,
    padding: 20,
    textAlign: "left",
    boxShadow: "0 0 60px rgba(59,130,246,0.06)",
  },
  windowDots: { display: "flex", gap: 6, marginBottom: 16 },
  windowDot: {
    width: 12,
    height: 12,
    borderRadius: "50%",
    display: "inline-block",
  },
  codePre: { margin: 0, fontSize: 13, lineHeight: 1.8 },
  codeLine: { display: "flex", gap: 16 },
  lineNum: { color: "#334155", minWidth: 20, userSelect: "none" },
  lineCode: { flex: 1 },
  section: {
    padding: "80px 80px",
    position: "relative",
    zIndex: 1,
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginBottom: 40,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: 700,
    color: "#E2E8F0",
    margin: "0 0 6px",
    letterSpacing: "0.02em",
  },
  sectionSub: { color: "#475569", fontSize: 14, margin: 0 },
  viewAll: {
    color: "#10B981",
    fontSize: 12,
    letterSpacing: "0.1em",
    textDecoration: "none",
  },
  projectsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: 20,
  },
  projectCard: {
    background: "#0D1424",
    border: "1px solid rgba(59,130,246,0.12)",
    borderRadius: 8,
    overflow: "hidden",
    transition: "border-color 0.2s, transform 0.2s",
  },
  projectThumb: {
    height: 160,
    background: "#111827",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderBottom: "1px solid rgba(59,130,246,0.08)",
  },
  thumbIcon: { fontSize: 32, opacity: 0.3 },
  projectBody: { padding: 20 },
  tagsRow: { display: "flex", gap: 8, marginBottom: 12 },
  tag: {
    fontSize: 11,
    border: "1px solid",
    padding: "3px 10px",
    borderRadius: 4,
    letterSpacing: "0.06em",
    fontWeight: 600,
  },
  projectTitle: {
    fontSize: 15,
    fontWeight: 700,
    margin: "0 0 8px",
    letterSpacing: "0.02em",
  },
  projectDesc: {
    color: "#64748B",
    fontSize: 13,
    lineHeight: 1.6,
    margin: 0,
  },
  stackSection: {
    background: "rgba(15,23,42,0.5)",
    borderTop: "1px solid rgba(59,130,246,0.08)",
    borderBottom: "1px solid rgba(59,130,246,0.08)",
  },
  stackGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(4, 1fr)",
    gap: 20,
    maxWidth: 800,
    margin: "0 auto",
  },
  stackCard: {
    background: "#0D1424",
    border: "1px solid rgba(59,130,246,0.12)",
    borderRadius: 8,
    padding: 28,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    textAlign: "center",
  },
  stackIcon: { fontSize: 28, marginBottom: 4 },
  stackLabel: { fontSize: 14, fontWeight: 700, color: "#E2E8F0" },
  stackSub: { fontSize: 12, color: "#475569" },
  contactBox: {
    background: "#0D1424",
    border: "1px solid rgba(59,130,246,0.15)",
    borderRadius: 12,
    padding: "60px",
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 60,
    boxShadow: "0 0 80px rgba(59,130,246,0.04)",
  },
  contactLeft: {},
  contactTitle: {
    fontSize: 28,
    fontWeight: 700,
    lineHeight: 1.3,
    margin: "0 0 16px",
    color: "#E2E8F0",
  },
  contactSub: {
    color: "#475569",
    fontSize: 14,
    lineHeight: 1.7,
    margin: "0 0 24px",
  },
  contactMeta: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    fontSize: 13,
    color: "#64748B",
  },
  contactRight: { display: "flex", flexDirection: "column", gap: 12 },
  contactInput: {
    background: "#111827",
    border: "1px solid rgba(59,130,246,0.2)",
    borderRadius: 4,
    padding: "12px 16px",
    color: "#94A3B8",
    fontSize: 13,
    fontFamily: "'JetBrains Mono', monospace",
    outline: "none",
  },
  contactTextarea: { height: 90, resize: "vertical" as const },
  initBtn: {
    background: "#3B82F6",
    border: "none",
    color: "#fff",
    padding: "14px",
    borderRadius: 4,
    cursor: "pointer",
    fontSize: 13,
    fontFamily: "inherit",
    fontWeight: 700,
    letterSpacing: "0.1em",
    marginTop: 4,
  },
  footer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "28px 80px",
    borderTop: "1px solid rgba(59,130,246,0.1)",
    position: "relative",
    zIndex: 1,
  },
  footerLogo: {
    color: "#E2E8F0",
    fontWeight: 700,
    fontSize: 14,
    letterSpacing: "0.1em",
  },
  footerLinks: { display: "flex", gap: 28 },
  footerLink: {
    color: "#475569",
    textDecoration: "none",
    fontSize: 13,
    transition: "color 0.2s",
  },
  footerCopy: { color: "#334155", fontSize: 12, letterSpacing: "0.04em" },
};
